### ISSUE TITLE
Can't get blocks to show up

### ISSUE THREAD

**Issue by naps62** [paradigmxyz/rivet#19]
what I did:

1. setup the repo as described in the readme
2. `pnpm dev`, along with running my own demo app: https://github.com/iron-wallet/web3-demo (this app boots anvil and immediatelly runs a forge script to seed initial setup)
3. submit some regular ETH transfers via the Test Dapp UI

During all this time, the "Blocks" tab was always as shown below. transaction

console shows only one error that seems unrelated (pasted below as well)

![image](https://github.com/paradigmxyz/rivet/assets/283819/22f4257a-5343-4270-bf9e-e14a6c028544)

```
console.js:213 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at ColorSchemeProvider (http://localhost:5173/src/design-system/ColorSchemeProvider.tsx:25:3)
    at http://localhost:5173/src/design-system/components/Box.tsx:26:7
    at _c (http://localhost:5173/src/design-system/components/Input.tsx:58:3)
    at div
    at http://localhost:5173/src/design-system/components/Box.tsx:26:7
    at div
    at http://localhost:5173/src/design-system/components/Box.tsx:26:7
    at _c (http://localhost:5173/src/design-system/components/Inline.tsx:30:3)
    at div
    at http://localhost:5173/src/design-system/components/Box.tsx:26:7
    at Stack2 (http://localhost:5173/src/design-system/components/Stack.tsx:25:3)
    at SendTransaction (http://localhost:5173/test-dapp/App.tsx:341:20)
    at div
    at http://localhost:5173/src/design-system/components/Box.tsx:26:7
    at Stack2 (http://localhost:5173/src/design-system/components/Stack.tsx:25:3)
    at div
    at ColorSchemeProvider (http://localhost:5173/src/design-system/ColorSchemeProvider.tsx:25:3)
    at http://localhost:5173/src/design-system/components/Box.tsx:26:7
    at App (http://localhost:5173/test-dapp/App.tsx:27:27)
```

**Comment by jxom** [comment]
Fixed on fe16c28ebc8427d988d188340c36b5b719c131af. Thanks!
